package com.example.util

import com.example.data.model.AppLanguage

object AppStrings {
    fun get(key: String, language: AppLanguage): String {
        return if (language == AppLanguage.BENGALI) {
            bengaliStrings[key] ?: englishStrings[key] ?: key
        } else {
            englishStrings[key] ?: key
        }
    }

    private val englishStrings = mapOf(
        "app_name" to "SuDhan",
        "app_full_name" to "SuDhan – Smart Interest & Lending Manager",
        "tagline" to "Your Money. Your Interest. Your Control.",
        "nav_home" to "Home",
        "nav_customers" to "Customers",
        "nav_add" to "Add",
        "nav_reports" to "Reports",
        "nav_settings" to "Settings",
        "nav_calculator" to "Calculator",
        "nav_transactions" to "Transactions",

        // Dashboard
        "total_lent" to "Total Lent",
        "total_borrowed" to "Total Borrowed",
        "principal_outstanding" to "Principal Outstanding",
        "interest_receivable" to "Interest Receivable",
        "interest_payable" to "Interest Payable",
        "interest_earned" to "Interest Earned",
        "interest_paid" to "Interest Paid",
        "net_profit" to "Net Interest Profit",
        "active_loans" to "Active Loans",
        "completed_loans" to "Completed Loans",
        "overdue_loans" to "Overdue Loans",
        "today_collection" to "Today's Collection",
        "upcoming_payments" to "Upcoming Payments",
        "financial_overview" to "Financial Overview",
        "monthly_profit_trend" to "Monthly Profit & Loss",
        "lending_vs_borrowing" to "Lending vs Borrowing",
        "overdue_alerts" to "Overdue Alerts",
        "upcoming_dues" to "Upcoming Dues",
        "no_overdue" to "No overdue loans. Great job!",
        "view_all" to "View All",

        // Actions
        "money_lent" to "Money Lent",
        "money_borrowed" to "Money Borrowed",
        "record_payment" to "Record Payment",
        "add_customer" to "Add Customer",
        "new_loan" to "New Loan",

        // Forms
        "customer_name" to "Customer Name",
        "lender_name" to "Lender Name",
        "mobile_number" to "Mobile Number",
        "address" to "Address",
        "principal_amount" to "Principal Amount",
        "start_date" to "Loan Start Date",
        "due_date" to "Due Date",
        "interest_rate" to "Interest Rate (%)",
        "interest_period" to "Interest Period",
        "interest_type" to "Interest Type",
        "repayment_freq" to "Repayment Frequency",
        "notes" to "Notes",
        "save" to "Save",
        "cancel" to "Cancel",
        "submit" to "Submit",
        "calculate" to "Calculate",
        "select_customer" to "Select Customer / Lender",
        "select_loan" to "Select Loan",
        "payment_type" to "Payment Type",
        "payment_mode" to "Payment Mode",
        "principal_component" to "Principal Component",
        "interest_component" to "Interest Component",
        "auto_split" to "Auto-Split Payment",

        // Interest types
        "simple_interest" to "Simple Interest",
        "compound_interest" to "Compound Interest",
        "flat_interest" to "Flat Interest",
        "reducing_balance" to "Reducing Balance",
        "emi_calculator" to "EMI Calculator",
        "daily_interest" to "Daily Interest",
        "monthly_interest" to "Monthly Interest",

        // Reports
        "reports_title" to "Financial Reports",
        "daily_collection_report" to "Daily Collection",
        "weekly_report" to "Weekly Report",
        "monthly_report" to "Monthly Report",
        "interest_earned_report" to "Interest Earned",
        "interest_paid_report" to "Interest Paid",
        "customer_wise_report" to "Customer Statement",
        "outstanding_report" to "Outstanding Balances",
        "overdue_report" to "Overdue Loans",
        "pnl_report" to "Profit & Loss",
        "export_csv" to "Export CSV",
        "filter_today" to "Today",
        "filter_yesterday" to "Yesterday",
        "filter_this_week" to "This Week",
        "filter_this_month" to "This Month",
        "filter_this_year" to "This Year",
        "filter_all" to "All Time",

        // Settings
        "settings_title" to "Settings",
        "appearance" to "Appearance",
        "theme" to "Theme",
        "language" to "Language",
        "security" to "Security & App Lock",
        "pin_lock" to "PIN Lock",
        "set_pin" to "Set 4-Digit PIN",
        "change_pin" to "Change PIN",
        "backup_restore" to "Backup & Restore",
        "create_backup" to "Create JSON Backup",
        "restore_backup" to "Restore from Backup",
        "export_all_csv" to "Export All Data (CSV)",
        "security_warning" to "Restoring backup will replace existing data.",
        "defaults" to "Loan Defaults",
        "default_interest_type" to "Default Interest Type",
        "default_interest_period" to "Default Interest Period"
    )

    private val bengaliStrings = mapOf(
        "app_name" to "সুধান",
        "app_full_name" to "সুধান – স্মার্ট সুদ ও ঋণ ম্যানেজার",
        "tagline" to "আপনার টাকা। আপনার সুদ। আপনার নিয়ন্ত্রণ।",
        "nav_home" to "হোম",
        "nav_customers" to "গ্রাহক",
        "nav_add" to "যোগ করুন",
        "nav_reports" to "রিপোর্ট",
        "nav_settings" to "সেটিংস",
        "nav_calculator" to "ক্যালকুলেটর",
        "nav_transactions" to "লেনদেন",

        // Dashboard
        "total_lent" to "মোট প্রদত্ত ঋণ",
        "total_borrowed" to "মোট গৃহীত ঋণ",
        "principal_outstanding" to "বাকি মূলধন",
        "interest_receivable" to "পাওনা সুদ",
        "interest_payable" to "দেনা সুদ",
        "interest_earned" to "অর্জিত সুদ",
        "interest_paid" to "পরিশোধিত সুদ",
        "net_profit" to "নিট সুদ মুনাফা",
        "active_loans" to "চলতি ঋণ",
        "completed_loans" to "পরিশোধিত ঋণ",
        "overdue_loans" to "মেয়াদোত্তীর্ণ ঋণ",
        "today_collection" to "আজকের আদায়",
        "upcoming_payments" to "আসন্ন কিস্তি",
        "financial_overview" to "আর্থিক সারসংক্ষেপ",
        "monthly_profit_trend" to "মাসিক লাভ ও ক্ষতি",
        "lending_vs_borrowing" to "ঋণ প্রদান বনাম ঋণ গ্রহণ",
        "overdue_alerts" to "বকেয়া সতর্কতা",
        "upcoming_dues" to "আসন্ন বকেয়া",
        "no_overdue" to "কোন মেয়াদোত্তীর্ণ ঋণ নেই। চমৎকার!",
        "view_all" to "সব দেখুন",

        // Actions
        "money_lent" to "টাকা দেওয়া (ঋণ দান)",
        "money_borrowed" to "টাকা নেওয়া (ঋণ গ্রহণ)",
        "record_payment" to "টাকা আদায় / পরিশোধ",
        "add_customer" to "নতুন গ্রাহক",
        "new_loan" to "নতুন ঋণ হিসাব",

        // Forms
        "customer_name" to "গ্রাহকের নাম",
        "lender_name" to "ঋণদাতার নাম",
        "mobile_number" to "মোবাইল নম্বর",
        "address" to "ঠিকানা",
        "principal_amount" to "মূলধনের পরিমাণ (টাকা)",
        "start_date" to "ঋণ শুরুর তারিখ",
        "due_date" to "পরিশোধের শেষ তারিখ",
        "interest_rate" to "সুদের হার (%)",
        "interest_period" to "সুদের মেয়াদ",
        "interest_type" to "সুদের ধরণ",
        "repayment_freq" to "কিস্তির সময়কাল",
        "notes" to "মন্তব্য",
        "save" to "সংরক্ষণ করুন",
        "cancel" to "বাতিল",
        "submit" to "জমা দিন",
        "calculate" to "হিসাব করুন",
        "select_customer" to "গ্রাহক / ঋণদাতা নির্বাচন করুন",
        "select_loan" to "ঋণ হিসাব নির্বাচন করুন",
        "payment_type" to "টাকা জমার ধরণ",
        "payment_mode" to "টাকা পরিশোধের মাধ্যম",
        "principal_component" to "মূলধন অংশ",
        "interest_component" to "সুদের অংশ",
        "auto_split" to "স্বয়ংক্রিয় ভাগ",

        // Interest types
        "simple_interest" to "সরল সুদ (Simple)",
        "compound_interest" to "চক্রবৃদ্ধি সুদ (Compound)",
        "flat_interest" to "ফ্ল্যাট সুদ (Flat)",
        "reducing_balance" to "হ্রাসমান ব্যালেন্স (Reducing)",
        "emi_calculator" to "ইএমআই ক্যালকুলেটর",
        "daily_interest" to "দৈনিক সুদ",
        "monthly_interest" to "মাসিক সুদ",

        // Reports
        "reports_title" to "আর্থিক বিবরণী ও রিপোর্ট",
        "daily_collection_report" to "দৈনিক আদায় রিপোর্ট",
        "weekly_report" to "সাপ্তাহিক রিপোর্ট",
        "monthly_report" to "মাসিক রিপোর্ট",
        "interest_earned_report" to "অর্জিত সুদ রিপোর্ট",
        "interest_paid_report" to "পরিশোধিত সুদ রিপোর্ট",
        "customer_wise_report" to "গ্রাহকভিত্তিক খতিয়ান",
        "outstanding_report" to "বাকি বকেয়া হিসাব",
        "overdue_report" to "মেয়াদোত্তীর্ণ ঋণের তালিকা",
        "pnl_report" to "লাভ ও ক্ষতি বিবরণী",
        "export_csv" to "CSV ফাইল এক্সপোর্ট",
        "filter_today" to "আজ",
        "filter_yesterday" to "গতকাল",
        "filter_this_week" to "এই সপ্তাহ",
        "filter_this_month" to "এই মাস",
        "filter_this_year" to "এই বছর",
        "filter_all" to "সর্বকালের",

        // Settings
        "settings_title" to "সেটিংস",
        "appearance" to "থিম ও ডিসপ্লে",
        "theme" to "থিম মোড",
        "language" to "ভাষা",
        "security" to "নিরাপত্তা ও পিন লক",
        "pin_lock" to "পিন লক",
        "set_pin" to "৪-সংখ্যার পিন দিন",
        "change_pin" to "পিন পরিবর্তন করুন",
        "backup_restore" to "ব্যাকআপ ও রিস্টোর",
        "create_backup" to "ব্যাকআপ ফাইল তৈরি করুন (JSON)",
        "restore_backup" to "ব্যাকআপ থেকে রিস্টোর করুন",
        "export_all_csv" to "সব তথ্য এক্সপোর্ট করুন (CSV)",
        "security_warning" to "রিস্টোর করলে আগের সকল তথ্য প্রতিস্থাপিত হবে।",
        "defaults" to "ডিফল্ট সেটিংস",
        "default_interest_type" to "ডিফল্ট সুদের ধরণ",
        "default_interest_period" to "ডিফল্ট সুদের মেয়াদ"
    )
}
